name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: sinoru/actions-setup-xcode@v2
      with:
        xcode-version: '13.4.1'
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
